import type { Manufacturer } from "./types";

/** GENERATED manufacturers discovered in the migration manifest (not in taxonomy.ts). */
export const generatedManufacturers: Manufacturer[] = [
  { slug: "chlorking", name: "ChlorKing", aka: ["ChlorKing, Inc."], url: "https://chlorking.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "stenner", name: "Stenner Pump Company", aka: [], url: "https://stenner.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "taylor-wharton", name: "Taylor-Wharton", aka: [], url: "https://twcryo.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "antiwave", name: "Anti Wave Global", aka: [], url: "https://www.antiwave.com/", relationship: "Carried in the Spectrum Aquatics catalogue, the deck-equipment line FreyTech represents for New York facilities. Availability, lead time and pricing are confirmed when you contact FreyTech.", relationshipStatus: "verified" },
  { slug: "competitor", name: "Competitor Swim", aka: [], url: "https://www.competitorswim.com/", relationship: "Carried in the Spectrum Aquatics catalogue, the deck-equipment line FreyTech represents for New York facilities. Availability, lead time and pricing are confirmed when you contact FreyTech.", relationshipStatus: "verified" },
  { slug: "duraflex", name: "Duraflex International", aka: [], url: "https://duraflexinternational.com/", relationship: "Carried in the Spectrum Aquatics catalogue, the deck-equipment line FreyTech represents for New York facilities. Availability, lead time and pricing are confirmed when you contact FreyTech.", relationshipStatus: "verified" },
  { slug: "speck-pumps", name: "Speck Pumps", aka: ["Speck Pumps (Speck Pumps-Pool Products, Inc.)"], url: "https://usa.speck-pumps.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "epd", name: "EPD USA", aka: ["EPD USA, Inc."], url: "https://epdusa.net/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "harmsco", name: "Harmsco", aka: ["Harmsco, Inc.", "Harmsco Filtration Products"], url: "https://harmsco.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "lochinvar", name: "Lochinvar", aka: ["Lochinvar, LLC"], url: "https://www.lochinvar.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "grundfos", name: "Grundfos", aka: ["Grundfos (PACO brand)"], url: "https://www.grundfos.com/us", relationship: "FreyTech represents this line for New York facilities through ASC Pumping Equipment, Inc. Availability, lead time and pricing are confirmed when you contact FreyTech.", relationshipStatus: "verified" },
  { slug: "safety-grip", name: "Safety Grip", aka: [], url: "https://safetygrip.net/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "aquastar", name: "AquaStar Pool Products", aka: [], url: "https://www.aquastarpoolproducts.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "paddock", name: "Paddock Pool Equipment", aka: ["Paddock Pool Equipment Company"], url: "https://www.paddockpoolequipment.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "wysiwash", name: "Wysiwash", aka: [], url: "https://www.wysiwash.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "jacks-magic", name: "Jack's Magic", aka: ["Jack's Magic Products, Inc."], url: "https://jacksmagic.com/", relationship: "FreyTech represents this line for New York facilities. Availability, lead time and pricing are confirmed when you contact FreyTech.", relationshipStatus: "verified" },
  { slug: "hammerhead", name: "Hammer-Head", aka: ["Hammer-Head Pool Vacuums"], url: "https://www.hammerheadvac.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "hexagone", name: "Hexagone", aka: ["Hexagone Manufacture SAS"], url: "https://myhexagone.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "lamotte", name: "LaMotte", aka: ["LaMotte Company"], url: "https://lamotte.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
  { slug: "palintest", name: "Palintest", aka: ["Palintest Ltd (a Halma company)"], url: "https://www.palintest.com/", relationship: "Products listed for evaluation; contact FreyTech to confirm availability, lead time, and service coverage. No dealer relationship is implied.", relationshipStatus: "pending-verification" },
];
