import type { Product } from "./types";
import { sources } from "@/content/products";

/**
 * Product records. Every specification traces to docs/research/products/claims-register.md
 * or docs/research/secondary-lines/. Records with status "draft" are never rendered.
 * Owner-approval and verification fields drive docs/PRODUCT-CONTENT-MATRIX.md.
 */
const V = "2026-09-15";

export const products: Product[] = [
  // ───────────────────────── Automated controls ─────────────────────────
  {
    slug: "becsys5", name: "BECSys5", manufacturer: "becs", category: "automated-controls", status: "published", availability: "confirmed", featured: true, flagshipHref: "/becsys5-controls/",
    aliases: ["BECSys 5", "BECS 5", "Precision Control MR3", "BECSys5 controller"], keywords: ["chemistry controller", "ORP controller", "remote monitoring", "BECSys Live", "alarms", "data logging", "VFD control"],
    headline: "Continuous chemistry control with alarms, records, and remote visibility for institutional pools",
    shortDescription: "Expandable water-chemistry controller: pH, ORP, and temperature standard; free-chlorine PPM, alkalinity, flow, pressures, inventory, VFD, UV, and heater control optional. Ethernet, alarms, and BECSys Live included.",
    overview: [
      "BECSys5 is BECS Technology's expandable controller for commercial pools. Out of the box it measures pH, ORP, and temperature through a machined flow cell with a flow switch, drives up to four chemical feeds on solid-state relays, logs a year of one-minute readings, and sends email and text alarms over its built-in Gigabit Ethernet connection.",
      "Optional sensors and modules extend it to true free-chlorine PPM control, total alkalinity, conductivity, turbidity, flow, pressures, tank levels, and chemical inventory, plus control of VFD recirculation pumps, UV, ozone, heaters, and makeup water and interfaces to building-management systems. Remote access through BECSys Live is included at no additional fee.",
    ],
    fit: { yes: ["Institutional pools that need alarms, records, and remote visibility", "Facilities replacing a discontinued or unsupported controller", "Multi-pool campuses standardizing on one platform", "Renovations integrating pumps, VFDs, UV, or heaters"], no: ["A single small pool that only needs pH/ORP with no communications (see BECSys3)", "Mechanical rooms that need automatic filter backwash from the controller (see BECSys7)"] },
    problems: ["stabilize-water-chemistry", "add-alarms-remote-visibility", "replace-obsolete-controller", "reduce-manual-testing", "improve-chemical-safety", "modernize-aging-equipment-room", "reduce-waste"],
    applications: ["Competition and lap pools", "Therapy pools and spas", "Municipal indoor and outdoor pools", "Multi-pool YMCAs and campuses"],
    facilities: ["municipal-aquatic-centers", "k12-schools", "colleges-universities", "ymca-community", "hotels-resorts-hospitality", "healthcare-rehabilitation", "camps-seasonal", "waterparks-high-load", "architects-engineers-public"],
    projectTypes: ["new-construction", "retrofit", "replacement"],
    features: ["pH, ORP, and temperature sensors, flow switch, and machined flow cell standard", "Four solid-state relays, expandable to 19 with SRX/MRX modules", "Gigabit Ethernet; email and text alarm notification", "One year of 1-minute readings and one year of events in non-volatile memory", "No-flow feed lockout, failsafe overfeed timers to 18 hours, pH-alarm sanitizer lockout, emergency off", "Three-level access codes", "NEMA 4X (IP66) enclosure; 115/230 VAC"],
    benefits: ["Fewer blind spots: dashboards, alarms, and trends reach the people responsible", "More consistent water through continuous control rather than periodic correction", "Records that can be reviewed with the health department alongside the required daily log", "Continuity through staff turnover: documented setpoints and logged changes", "One platform that grows as the mechanical room is modernized"],
    models: [
      { name: "BECSys5 standard", fit: "pH/ORP/temperature control with Ethernet, alarms, logging, and BECSys Live." },
      { name: "With free/total chlorine PPM", fit: "Direct PPM monitoring and control with optional sensors; combined-chlorine tracking." },
      { name: "With BECSys Alkalinity Meter", fit: "Total alkalinity monitoring and control." },
      { name: "With flow/pressure/VFD option", fit: "System flow, pressures, TDH monitoring and patented VFD recirculation-pump control via 4–20 mA output." },
      { name: "With BMS interface", fit: "Modbus TCP/IP, BACnet, Metasys N2, or LonWorks." },
    ],
    specs: [
      { k: "Standard measurements", v: "pH, ORP, temperature; flow switch", src: "TDS-4262" },
      { k: "Optional measurements", v: "Free/total/combined chlorine (PPM), total alkalinity, conductivity/TDS, turbidity, system flow, pressures, vacuum, TDH, tank levels, chemical inventory", src: "TDS-4262" },
      { k: "Outputs", v: "4 solid-state relays standard; up to 19 with expansion modules; optional 4–20 mA output", src: "TDS-4262" },
      { k: "Communications", v: "Gigabit Ethernet standard; optional Wi-Fi; optional Modbus TCP/IP, BACnet, Metasys N2, LonWorks", src: "TDS-4262" },
      { k: "Remote access", v: "BECSys Live (no fee), BECSys for Windows, BECSys Now! app", src: "SLS-4333-H" },
      { k: "Data logging", v: "365 days of 1-minute readings; 365 days of events; NAND flash, no battery", src: "TDS-4262" },
      { k: "Safety", v: "No-flow lockout with flow-restored delay; failsafe overfeed timers (1-minute steps to 18 h); pH-alarm sanitizer lockout; emergency off", src: "TDS-4262" },
      { k: "Enclosure / power", v: "Glass-reinforced polycarbonate, NEMA 4X (IP66); 115/230 VAC 50/60 Hz", src: "TDS-4262" },
      { k: "Listings", v: "NSF Certified and Listed to NSF/ANSI 50; ETL Listed to ANSI/UL 61010-1", src: "TDS-4262" },
      { k: "Warranty (manufacturer)", v: "5 years electronics; 2 years pH/ORP/temperature sensors; 1 year optional sensors and flow cell", src: "SLS-4333-H / TDS-4262" },
    ],
    prerequisites: ["A sound sample loop: adequate sample flow, strainer, and a location for the flow cell", "Feed equipment with controllable outputs (solenoids, metering pumps, feeder valves)", "115 or 230 VAC circuit", "Network drop or Wi-Fi option for alarms and BECSys Live", "Chemical storage and interlock wiring reviewed for New York requirements"],
    retrofit: ["Most replacements reuse the existing sample line and feed equipment with a new flow cell and probes", "Typical cutover is one to two days on site plus stabilization and training", "Adding sensors, relays, VFD, or BMS interfaces extends scope and may involve the engineer and permit-issuing official (6-1.8)"],
    integrations: [
      { name: "Pulsar Precision and Precision 30 feeders", note: "Feeder solenoid driven by the controller's chlorine-demand output.", status: "verified" },
      { name: "Metering pumps and CO2 pH control", note: "Standard relay outputs; CO2 systems per BECS literature.", status: "verified" },
      { name: "SpinTouch and Lumiso digital test kits", note: "Automatic upload of readings.", status: "verified" },
      { name: "VFDs, UV, ozone, heaters, autofill", note: "Configuration-dependent optional control functions.", status: "verified" },
      { name: "Building management systems", note: "Optional Modbus TCP/IP, BACnet, Metasys N2, LonWorks interfaces.", status: "verified" },
      { name: "BECSys ChemLock", note: "Independent UL 508A chemical-feed interlock.", status: "verified" },
    ],
    services: ["Assessment of the sample loop, feed equipment, network, and storage", "Configuration and submittals against your point list", "Installation by FreyTech technicians", "Commissioning: calibration against manual tests, setpoints, alarm limits, failsafe and no-flow tests, alarm delivery test, settings record", "Operator and supervisor training with written procedures"],
    support: ["Phone support and remote diagnostics through BECSys Live", "Preventive maintenance visits for calibration and probe replacement", "BECS warranty coordination", "Genuine replacement sensors and flow-cell parts"],
    docs: [
      { title: "BECSys5 brochure (SLS-4333-H)", type: "Brochure", href: sources.becsys5Brochure.href, fileType: "PDF", status: "linked" },
      { title: "BECSys Live brochure (SLS-6105-A)", type: "Brochure", href: sources.becsysLive.href, fileType: "PDF", status: "linked" },
      { title: "BECSys5 Technical Data Sheet (TDS-4262)", type: "Specification sheet", fileType: "PDF", status: "placeholder", note: "Official copy available to FreyTech through the BECS distributor portal; provided on request pending permission to host." },
      { title: "BECSys5 Operator's Manual", type: "Owner's manual", fileType: "PDF", status: "placeholder", note: "Provided to customers with the system; not publicly hosted by BECS." },
      { title: "BECSys5 Installation & Technical Manual", type: "Installation manual", fileType: "PDF", status: "placeholder", note: "Provided to installers and engineers on request." },
      { title: "BECS product page", type: "Product page", href: sources.becsysProducts.href, fileType: "Web", status: "linked" },
    ],
    faqs: [
      { q: "Do we need a separate controller for each pool?", a: "Yes. One BECSys5 controls one body of water. BECSys Live shows all of them together." },
      { q: "Does it replace manual testing in New York?", a: "No. Manual DPD tests and the State daily operation record remain required (10 NYCRR 6-1.11, 6-1.21). The controller's logs supplement them." },
      { q: "What does remote access cost?", a: "BECS states BECSys Live is included with no additional fees or subscription." },
      { q: "Can it control free chlorine directly?", a: "Yes, with the optional PPM sensor. Many sites control on ORP and monitor PPM; we recommend based on your water and staff." },
    ],
    related: ["becsys3", "becsys7", "becsys-chemlock", "becs-replacement-sensors"],
    specifiedWith: [{ slug: "pulsar-precision", status: "verified" }, { slug: "pulsar-precision-30", status: "verified" }, { slug: "becsys-chemlock", status: "verified" }, { slug: "taylor-test-kits", status: "commonly-considered" }],
    relatedSolutions: ["add-alarms-remote-visibility", "replace-obsolete-controller", "stabilize-water-chemistry"],
    seoTitle: "BECSys5 Commercial Pool Chemical Controller | Specs, Fit, and Installation in New York",
    seoDescription: "BECSys5 water-chemistry controller specifications, standard and optional capabilities, installation prerequisites, retrofit notes, and FreyTech's commissioning and service in New York State outside NYC.",
    sourceUrls: [sources.becsys5Brochure.href, sources.becsysLive.href, "https://www.commercialaquaticsupplies.com/wp-content/uploads/2023/08/TDS-4262-K_BECSys5.pdf"],
    claimStatus: "verified", lastVerified: V, ownerApproved: false,
  },
  {
    slug: "becsys3", name: "BECSys3", manufacturer: "becs", category: "automated-controls", status: "published", availability: "confirmed", aliases: ["BECSys 3", "BECS 3", "Precision Control MR2"],
    headline: "Straightforward pH and ORP control for a single pool, with PPM and remote access as options",
    shortDescription: "Entry-level BECS controller with a two-line display, pH/ORP control, optional free-chlorine sensor, and an optional Communications module for BECSys Live.",
    overview: ["BECSys3 is the simplest BECS controller: pH and ORP control on a two-line backlit display. It can be upgraded with a free-chlorine PPM sensor and with a Communications module that adds BECSys Live remote access. It suits a single pool with a trained operator where the expandable monitoring of BECSys5 is not needed."],
    fit: { yes: ["A single commercial pool or spa needing reliable pH/ORP control", "Budget-constrained replacements of a basic controller", "Facilities that may add communications later"], no: ["Multi-point monitoring (flow, pressures, inventory) or equipment-room control", "Facilities that need alarms and remote visibility from day one without the Communications option"] },
    problems: ["stabilize-water-chemistry", "replace-obsolete-controller", "reduce-manual-testing"],
    applications: ["Single-pool schools, hotels, camps, and clubs", "Spas and small therapy pools"],
    facilities: ["k12-schools", "hotels-resorts-hospitality", "camps-seasonal", "ymca-community", "healthcare-rehabilitation"],
    projectTypes: ["retrofit", "replacement"],
    features: ["pH and ORP control", "Two-line backlit display", "Optional free-chlorine PPM sensor", "Optional Communications module with BECSys Live access"],
    benefits: ["Consistent control at a lower entry cost", "Upgrade path to PPM and remote access", "Same BECS sensors and FreyTech support as the larger models"],
    specs: [
      { k: "Control", v: "pH and ORP; optional free-chlorine PPM", src: "SLS-4655-E" },
      { k: "Display", v: "Two-line backlit", src: "SLS-4655-E" },
      { k: "Communications", v: "Optional; supports 24/7 access through BECSys Live", src: "SLS-4655-E" },
    ],
    prerequisites: ["Sample loop and flow cell location", "Controllable feed equipment", "Power circuit; network only if Communications option is used"],
    retrofit: ["Like-for-like replacement of basic pH/ORP controllers", "Consider BECSys5 if the facility is likely to want alarms, logging, or additional points within its capital cycle"],
    integrations: [{ name: "Metering pumps and erosion feeders", note: "Relay outputs switch feed equipment.", status: "verified" }, { name: "BECSys Live", note: "Requires the Communications option.", status: "verified" }],
    services: ["Assessment and configuration", "Installation and commissioning", "Operator training"],
    support: ["Phone support", "Preventive maintenance and sensor replacement", "BECS warranty coordination"],
    docs: [{ title: "BECSys3 brochure (SLS-4655-E)", type: "Brochure", href: "https://www.becsys.com/wp-content/uploads/2021/06/SLS-4655-E_BECSys3.pdf", fileType: "PDF", status: "linked" }, { title: "BECS product page", type: "Product page", href: sources.becsysProducts.href, fileType: "Web", status: "linked" }],
    faqs: [{ q: "Can a BECSys3 be seen remotely?", a: "Yes, when equipped with the Communications option, which supports BECSys Live." }],
    related: ["becsys5", "becs-replacement-sensors"],
    specifiedWith: [{ slug: "taylor-test-kits", status: "commonly-considered" }],
    relatedSolutions: ["replace-obsolete-controller"],
    seoTitle: "BECSys3 Pool Chemical Controller | Entry-Level pH/ORP Control, New York",
    seoDescription: "BECSys3 controller for single commercial pools: pH/ORP control, optional PPM sensor, optional BECSys Live communications. Installed and supported by FreyTech in New York State outside NYC.",
    sourceUrls: ["https://www.becsys.com/wp-content/uploads/2021/06/SLS-4655-E_BECSys3.pdf"],
    claimStatus: "verified", lastVerified: V, ownerApproved: false,
  },
  {
    slug: "becsys7", name: "BECSys7", manufacturer: "becs", category: "automated-controls", status: "published", availability: "confirmed",
    headline: "Chemistry control plus automatic filter backwash for the largest mechanical rooms",
    shortDescription: "BECS's top controller: everything in BECSys5 plus automatic backwash for up to 16 filters, five mechanical relays, and UV/heater interfaces.",
    overview: ["BECSys7 extends the BECSys5 platform for large mechanical rooms. Its distinguishing capability is automatic filter backwash for up to 16 filters, alongside five standard mechanical relays and interfaces for UV and heaters. It suits aquatic centers and natatoriums where filtration sequencing belongs in the same controller as chemistry."],
    fit: { yes: ["Aquatic centers with multiple filters that should backwash automatically", "New construction where one controller should run chemistry and filtration sequencing"], no: ["Facilities that only need chemistry control and monitoring (BECSys5 is the better fit)"] },
    problems: ["modernize-aging-equipment-room", "add-alarms-remote-visibility", "replace-obsolete-controller"],
    applications: ["Large natatoriums and aquatic centers", "Waterparks with multiple filter banks"],
    facilities: ["municipal-aquatic-centers", "colleges-universities", "waterparks-high-load", "architects-engineers-public"],
    projectTypes: ["new-construction", "retrofit"],
    features: ["Automatic filter backwash for up to 16 filters (optional)", "Five standard mechanical relay outputs", "UV and heater interfaces", "BECSys5 chemistry, logging, alarms, and BECSys Live"],
    benefits: ["Filtration and chemistry sequenced from one documented system", "Fewer manual backwash routines in large rooms", "Same remote visibility and records as BECSys5"],
    specs: [
      { k: "Filter backwash", v: "Automatic backwash for up to 16 filters (optional)", src: "SLS-4335-F" },
      { k: "Relays", v: "Five standard mechanical relay outputs", src: "TDS-4263" },
      { k: "Interfaces", v: "UV and heater interfaces; BECSys5-class chemistry and communications", src: "SLS-4335-F" },
    ],
    prerequisites: ["Filter valves and actuators compatible with automatic backwash sequencing", "Engineer-led design of the backwash sequence", "Network, power, and sample loop as for BECSys5"],
    retrofit: ["Usually part of a filtration or mechanical-room renovation rather than a controller-only replacement"],
    integrations: [{ name: "Filter valve actuators", note: "Sequenced backwash per engineer's design.", status: "verified" }, { name: "UV and heaters", note: "Interfaces per BECS literature.", status: "verified" }],
    services: ["Design coordination with the engineer of record", "Installation and commissioning of chemistry and backwash sequences", "Operator training"],
    support: ["Remote diagnostics through BECSys Live", "Preventive maintenance", "BECS warranty coordination"],
    docs: [{ title: "BECSys7 brochure (SLS-4335-F)", type: "Brochure", href: "https://www.becsys.com/wp-content/uploads/sites/2/2025/10/SLS-4335-F_BECSys7.pdf", fileType: "PDF", status: "linked" }, { title: "BECSys7 Technical Data Sheet (TDS-4263)", type: "Specification sheet", fileType: "PDF", status: "placeholder", note: "Available on request through FreyTech." }],
    faqs: [{ q: "Do we need BECSys7 to control a VFD or UV?", a: "No. BECSys5 offers optional VFD, UV, ozone, and heater control. BECSys7 adds automatic filter backwash and mechanical relays." }],
    related: ["becsys5", "defender-regenerative-media-filter"],
    specifiedWith: [{ slug: "pulsar-precision", status: "verified" }, { slug: "defender-regenerative-media-filter", status: "commonly-considered" }],
    relatedSolutions: ["modernize-aging-equipment-room"],
    seoTitle: "BECSys7 Controller with Automatic Filter Backwash | New York Aquatic Centers",
    seoDescription: "BECSys7 combines BECSys5 chemistry control with automatic backwash for up to 16 filters. Design coordination, installation, and support by FreyTech in New York State outside NYC.",
    sourceUrls: ["https://www.becsys.com/wp-content/uploads/sites/2/2025/10/SLS-4335-F_BECSys7.pdf"],
    claimStatus: "verified", lastVerified: V, ownerApproved: false,
  },
  {
    slug: "becsys-chemlock", name: "BECSys ChemLock", manufacturer: "becs", category: "automated-controls", subcategory: "Safety interlocks", status: "published", availability: "confirmed",
    headline: "An independent interlock that stops chemical feed whenever the circulation pump is not running",
    shortDescription: "UL 508A-approved interlock panel that locks out chemical feeds independently of the controller when circulation stops.",
    overview: ["ChemLock provides a second, independent mechanism for locking out chemical feed when the circulation pump is not running. It complements the controller's own no-flow lockout so that a single failure cannot allow chemical to feed into a stagnant line. BECS lists it as UL 508A approved."],
    fit: { yes: ["Facilities that want an independent feed interlock in addition to the controller", "Renovations where the engineer specifies redundant chemical-feed safety"], no: ["Sites without a controllable feed system to interlock"] },
    problems: ["improve-chemical-safety"],
    applications: ["Any commercial pool with pumped or erosion chemical feed"],
    facilities: ["municipal-aquatic-centers", "k12-schools", "colleges-universities", "ymca-community", "healthcare-rehabilitation", "waterparks-high-load", "architects-engineers-public"],
    projectTypes: ["new-construction", "retrofit", "replacement"],
    features: ["Independent lockout of chemical feeds when the circulation pump is off", "UL 508A approved panel", "Works alongside BECSys controllers"],
    benefits: ["Defense in depth for the requirement that feeders deactivate without recirculation flow (10 NYCRR 6-1.29 item 11.7)", "Clear, inspectable safety function for engineers and health departments"],
    specs: [{ k: "Function", v: "Independent chemical-feed lockout tied to circulation pump status", src: "SLS-6152-A" }, { k: "Approval", v: "UL 508A approved", src: "SLS-6152-A" }],
    prerequisites: ["Circulation pump status signal", "Controllable feed equipment"],
    retrofit: ["Typically added during a controller replacement or feed-system upgrade"],
    integrations: [{ name: "BECSys3/5/7", note: "Designed to work with BECS controllers.", status: "verified" }, { name: "Pulsar feeders and metering pumps", note: "Interlocks the feed power/solenoid circuit.", status: "commonly-considered" }],
    services: ["Specification support", "Installation and interlock testing at commissioning"],
    support: ["Annual interlock verification within service agreements"],
    docs: [{ title: "BECSys ChemLock brochure (SLS-6152-A)", type: "Brochure", href: sources.chemLock.href, fileType: "PDF", status: "linked" }],
    faqs: [{ q: "Doesn't the controller already stop feed on no flow?", a: "Yes. ChemLock adds an independent path so the safety function does not depend on a single device." }],
    related: ["becsys5"], specifiedWith: [{ slug: "becsys5", status: "verified" }, { slug: "pulsar-precision", status: "commonly-considered" }],
    relatedSolutions: ["improve-chemical-safety"],
    seoTitle: "BECSys ChemLock Chemical-Feed Interlock | Pool Chemical Safety, New York",
    seoDescription: "Independent UL 508A chemical-feed interlock for commercial pools, installed with BECSys controllers by FreyTech in New York State outside NYC.",
    sourceUrls: [sources.chemLock.href], claimStatus: "verified", lastVerified: V, ownerApproved: false,
  },
  // ───────────────────────── Chemical delivery ─────────────────────────
  {
    slug: "pulsar-precision", name: "Pulsar Precision", manufacturer: "pulsar", category: "chemical-delivery-chlorination", status: "published", availability: "request", featured: true, flagshipHref: "/pulsar-precision-feeders/",
    aliases: ["PS-1HCE", "Pulsar HCE", "Pulsar 500 replacement", "Pulsar 140 replacement", "cal hypo feeder"], keywords: ["calcium hypochlorite", "chlorinator", "briquette feeder", "large pool chlorination", "waterpark chlorination"],
    headline: "High-capacity calcium hypochlorite feed for very large pools and peak bather loads",
    shortDescription: "Patented high-capacity erosion feeder for calcium hypochlorite briquettes; manufacturer-rated for 500,000 to 1,000,000+ gallon pools; up to 189 lb/day available chlorine.",
    overview: ["Pulsar Precision (model PS-1HCE) erodes Pulsar Plus calcium hypochlorite briquettes into a concentrated chlorine solution on demand from the chemistry controller. Pulsar positions it for very large pools, water parks, and competition venues. It replaces bulk liquid bleach or gas chlorine with a dry chemical stored as a solid.", "FreyTech qualifies each site by measured chlorine demand, hydraulics, storage, and code, not by brochure gallonage, and installs the feeder with a booster/Venturi loop, controller interlocks, and operator training."],
    fit: { yes: ["50-meter and large competition pools", "Municipal aquatic centers and waterparks with heavy summer loads", "Large institutional pools leaving liquid bleach or gas chlorine"], no: ["Most school, YMCA, hotel, and therapy pools (see Precision 30 or controlled liquid feed)", "Sites without safe, ventilated dry-chemical storage"] },
    problems: ["replace-liquid-chlorine", "improve-chemical-safety", "modernize-aging-equipment-room", "reduce-waste", "prepare-specifications-budgets"],
    applications: ["Competition venues", "Municipal aquatic centers", "Waterparks", "Large university natatoriums"],
    facilities: ["municipal-aquatic-centers", "colleges-universities", "waterparks-high-load", "architects-engineers-public"],
    projectTypes: ["new-construction", "retrofit", "replacement"],
    features: ["Patented high-capacity erosion (HCE) feed system", "100 lb hopper plus 50 lb reserve of briquettes", "Delivers up to 189 lb/day available chlorine (max 7.8 lb/hr)", "NSF Listed per Pulsar", "Switched by the controller's chlorine-demand output", "Customizable skid option"],
    benefits: ["No bulk liquid storage or degradation", "Capacity for meet-day and heat-wave demand", "Less chemical volume handled for the same available chlorine", "Dry chemical with long shelf life"],
    models: [{ name: "Pulsar Precision (PS-1HCE)", fit: "Very large pools; booster-pump/Venturi loop." }, { name: "Pulsar Precision 30 (PS-1HCE30)", fit: "Small and mid-size commercial pools; flow-based Venturi. See its own page." }],
    specs: [
      { k: "Chlorine delivery (pools)", v: "5–189 lb available chlorine/day; max 7.8 lb/hr", src: "O&I Manual Rev 1.0 (2020), Table 8" },
      { k: "Solution strength", v: "0.6–0.8% at 84 °F inlet", src: "O&I Manual, Table 8" },
      { k: "Dry chemical capacity", v: "100 lb + 50 lb reserve", src: "O&I Manual, Table 7" },
      { k: "Dimensions / weight", v: "29.8 × 25.3 × 40.9 in; ~220 lb operating", src: "O&I Manual, Table 7" },
      { k: "Water supply", v: "Booster pump/Venturi loop; 2.5–3.5 gpm at 30–40 psig", src: "O&I Manual, Table 5" },
      { k: "Electrical", v: "120/240 VAC, 1-phase, 15–20 A", src: "O&I Manual, Table 5" },
      { k: "Listing", v: "NSF Listed (standard not stated by Pulsar)", src: "pulsarpools.com" },
      { k: "Warranty (manufacturer)", v: "12 months from installation or 18 months from shipment", src: "O&I Manual" },
    ],
    prerequisites: ["Measured chlorine demand justifying the capacity", "Segregated, ventilated dry-oxidizer storage meeting fire code", "Booster pump and Venturi loop with injection point", "120/240 VAC circuit", "Controller with chlorine-demand output and flow interlock", "Plan review with the engineer where treatment equipment is modified (6-1.8)"],
    retrofit: ["Common conversion from liquid bleach or gas chlorine at large venues", "Expect calcium hardness to rise; plan pH control and water replacement", "Storage often determines feasibility more than the feeder itself"],
    integrations: [{ name: "BECSys5 / BECSys7", note: "Controller demand output drives the feeder solenoid.", status: "verified" }, { name: "Pulsar GuardTec", note: "Pulsar's own pH/ORP controller.", status: "verified" }, { name: "BECSys ChemLock", note: "Independent feed interlock.", status: "commonly-considered" }],
    services: ["Demand assessment and storage review", "Loop design and coordination with the engineer", "Installation, delivery verification, interlock tests, settings record", "Operator training on loading, cleaning, and alarms"],
    support: ["Scheduled hopper, nozzle, and solution-tank cleaning", "Wear parts and briquette supply planning", "Pulsar warranty coordination"],
    docs: [
      { title: "Pulsar Precision product page", type: "Product page", href: sources.pulsarPrecision.href, fileType: "Web", status: "linked" },
      { title: "Pulsar Precision Operation & Installation Manual (Rev 1.0, 2020)", type: "Installation manual", fileType: "PDF", status: "placeholder", note: "Available from Pulsar's support page; provided by FreyTech on request." },
      { title: "Pulsar support and manuals", type: "Engineering resource", href: sources.pulsarSupport.href, fileType: "Web", status: "linked" },
      { title: "Pulsar Plus briquettes SDS", type: "Safety data sheet", href: sources.pulsarBriquetteSDS.href, fileType: "PDF", status: "linked" },
    ],
    faqs: [{ q: "How do we know if our pool is big enough?", a: "By chlorine demand. We look at daily chlorine use, bather load, temperature, and exposure. Pulsar's published gallonage is a starting point only." }, { q: "Do we need a Pulsar controller?", a: "No. The feeder is driven by any controller with a chlorine-demand output; FreyTech commonly pairs it with BECSys5." }],
    related: ["pulsar-precision-30", "pulsar-plus-briquettes", "becsys5"],
    specifiedWith: [{ slug: "becsys5", status: "verified" }, { slug: "becsys-chemlock", status: "commonly-considered" }, { slug: "pulsar-plus-briquettes", status: "verified" }],
    relatedSolutions: ["replace-liquid-chlorine", "improve-chemical-safety"],
    seoTitle: "Pulsar Precision Calcium Hypochlorite Feeder | Specs and Installation, New York",
    seoDescription: "Pulsar Precision cal hypo feeder: capacity, requirements, storage, controller pairing, and FreyTech's demand-based sizing, installation, and service for large pools in New York State outside NYC.",
    sourceUrls: [sources.pulsarPrecision.href, sources.pulsarSupport.href, sources.pulsarBriquetteSDS.href], claimStatus: "partially-verified", lastVerified: V, ownerApproved: false,
    ownerNotes: "Full-size manual read from a dealer host; obtain official copy. Confirm Pulsar dealer status.",
  },
  {
    slug: "pulsar-precision-30", name: "Pulsar Precision 30", manufacturer: "pulsar", category: "chemical-delivery-chlorination", status: "published", availability: "request", flagshipHref: "/pulsar-precision-feeders/",
    aliases: ["PS-1HCE30", "Precision30", "Pulsar 45 replacement", "Pulsar 1 replacement", "Mini HCE"], keywords: ["calcium hypochlorite", "chlorinator", "mid-size pool chlorination", "flow-based feeder"],
    headline: "Compact, flow-based calcium hypochlorite feed for small and mid-size commercial pools",
    shortDescription: "Flow-based erosion feeder with a 30 lb hopper; 2–36 lb/day available chlorine; manufacturer guidance up to 200,000 gallons indoor.",
    overview: ["Precision 30 (model PS-1HCE30) brings dry calcium hypochlorite feed to pools far smaller than the full-size Precision serves. Its standard installation is flow-based through a Venturi bypass, with no booster pump, and its ~50 lb operating weight fits tight mechanical rooms.", "Pulsar's web page gives conflicting pool-size figures; its installation manual's guidance is up to 200,000 gallons indoor and 90,000 gallons outdoor non-stabilized. Because New York prohibits stabilizer, the non-stabilized figure applies outdoors. FreyTech sizes by measured demand."],
    fit: { yes: ["School, YMCA, hotel, and municipal pools moving off liquid bleach", "Facilities with limited storage or delivery access", "Mid-size pools whose demand exceeds small tablet feeders"], no: ["Very large or high-load pools (see Pulsar Precision)", "Small warm therapy pools and spas where controls matter more than feed capacity"] },
    problems: ["replace-liquid-chlorine", "improve-chemical-safety", "modernize-aging-equipment-room"],
    applications: ["Mid-size lap pools", "Hotel and resort pools", "Camp and seasonal pools", "Outdoor municipal pools within demand range"],
    facilities: ["k12-schools", "ymca-community", "hotels-resorts-hospitality", "camps-seasonal", "municipal-aquatic-centers", "colleges-universities"],
    projectTypes: ["new-construction", "retrofit", "replacement"],
    features: ["Flow-based Venturi bypass installation; no booster pump in the standard configuration", "30 lb hopper", "2–36 lb/day available chlorine (max 1.5 lb/hr)", "~50 lb operating weight; 19.5 × 15.5 × 34 in", "NSF Listed per Pulsar"],
    benefits: ["Dry chemical feed at a scale most institutional pools can use", "Small footprint and simple hydraulics", "Fewer deliveries and no bulk liquid storage"],
    specs: [
      { k: "Chlorine delivery (pools)", v: "2–36 lb available chlorine/day; max 1.5 lb/hr", src: "O&I Manual Rev 1.1 (2023), Table 12" },
      { k: "Manufacturer sizing guidance", v: "Indoor up to 200,000 gal; outdoor non-stabilized up to 90,000 gal; outdoor stabilized up to 150,000 gal (not applicable in NY); spas up to 15,000 gal", src: "O&I Manual Rev 1.1, Table 12" },
      { k: "Solution strength", v: "0.2–0.3%", src: "O&I Manual Rev 1.1" },
      { k: "Dry chemical capacity", v: "30 lb", src: "O&I Manual Rev 1.1, Table 11" },
      { k: "Dimensions / weight", v: "19.5 in D × 15.5 in W × 34 in H; ~50 lb operating", src: "O&I Manual Rev 1.1, Table 11" },
      { k: "Water supply", v: "Flow-based Venturi bypass; 1.25 gpm at 5 psi filter pressure (standard)", src: "O&I Manual Rev 1.1" },
      { k: "Listing", v: "NSF Listed (standard not stated)", src: "pulsarpools.com" },
      { k: "Warranty (manufacturer)", v: "12 months from installation or 18 months from shipment", src: "O&I Manual Rev 1.1" },
    ],
    prerequisites: ["Adequate filter pressure for the Venturi bypass, or booster-pump variant", "Controller with chlorine-demand output and flow interlock", "Dry-oxidizer storage per fire code", "Plan review with the engineer where treatment equipment is modified"],
    retrofit: ["Frequently replaces liquid metering pumps at mid-size pools", "Expect calcium hardness to rise; plan pH control", "Confirm demand from a season of records before sizing"],
    integrations: [{ name: "BECSys3 / BECSys5", note: "Controller demand output drives the feeder solenoid.", status: "verified" }, { name: "Pulsar GuardTec", note: "Pulsar's own controller.", status: "verified" }],
    services: ["Demand and storage assessment", "Installation and commissioning with delivery verification", "Operator training"],
    support: ["Scheduled cleaning and wear parts", "Briquette supply planning", "Pulsar warranty coordination"],
    docs: [
      { title: "Pulsar Precision 30 product page", type: "Product page", href: sources.pulsarPrecision30.href, fileType: "Web", status: "linked" },
      { title: "Pulsar Precision 30 Operation & Installation Manual (Rev 1.1, 2023)", type: "Installation manual", href: sources.pulsarPrecision30Manual.href, fileType: "PDF", status: "linked" },
      { title: "Precision 30 bid spec, CAD, footprint, schematics", type: "Engineering resource", href: sources.pulsarPrecision30Resources.href, fileType: "Web", status: "linked" },
      { title: "Pulsar Plus briquettes SDS", type: "Safety data sheet", href: sources.pulsarBriquetteSDS.href, fileType: "PDF", status: "linked" },
    ],
    faqs: [{ q: "Which pool-size figure should we believe?", a: "Pulsar's page lists 10,000–300,000, up to 100,000, and up to 300,000 gallons in different places. The manual's guidance is up to 200,000 gallons indoor. We size by measured chlorine demand." }],
    related: ["pulsar-precision", "pulsar-plus-briquettes", "becsys5", "becsys3"],
    specifiedWith: [{ slug: "becsys5", status: "verified" }, { slug: "pulsar-plus-briquettes", status: "verified" }],
    relatedSolutions: ["replace-liquid-chlorine"],
    seoTitle: "Pulsar Precision 30 Cal Hypo Feeder | Mid-Size Commercial Pools, New York",
    seoDescription: "Pulsar Precision 30 flow-based calcium hypochlorite feeder: verified capacity and sizing guidance, requirements, and FreyTech installation and service in New York State outside NYC.",
    sourceUrls: [sources.pulsarPrecision30.href, sources.pulsarPrecision30Manual.href], claimStatus: "verified", lastVerified: V, ownerApproved: false, ownerNotes: "Confirm Precision 30 is part of FreyTech's offering and dealer status.",
  },
  {
    slug: "pulsar-plus-briquettes", name: "Pulsar Plus Calcium Hypochlorite Briquettes", manufacturer: "pulsar", category: "parts-accessories-replacement", subcategory: "Chemicals", status: "published", availability: "request",
    headline: "The dry chemical Pulsar Precision feeders are designed and warranted to use",
    shortDescription: "Calcium hypochlorite briquettes for Pulsar Precision and Precision 30 feeders. Pulsar's warranty requires Pulsar Plus briquettes.",
    overview: ["Pulsar Plus briquettes are the calcium hypochlorite chemical the Precision feeders erode into chlorine solution. Both feeder manuals state that use of other chemicals voids the warranty. Storage, handling, and the safety data sheet apply to every site that runs a Pulsar feeder."],
    fit: { yes: ["Facilities operating Pulsar Precision or Precision 30 feeders"], no: ["Any other feeder type; do not mix chlorine products"] },
    problems: ["replace-liquid-chlorine"],
    applications: ["Pulsar feeder sites"],
    facilities: ["municipal-aquatic-centers", "colleges-universities", "k12-schools", "ymca-community", "waterparks-high-load", "hotels-resorts-hospitality", "camps-seasonal"],
    projectTypes: ["replacement"],
    features: ["Calcium hypochlorite briquettes for Pulsar erosion feeders", "EPA-registered pool chemical (see SDS)", "Supplied in original containers"],
    benefits: ["Preserves the Pulsar feeder warranty", "Long shelf life as a stored solid compared with bleach"],
    specs: [{ k: "Chemical", v: "Calcium hypochlorite (see SDS for composition)", src: "Pulsar Plus SDS" }, { k: "Compatible feeders", v: "Pulsar Precision, Precision 30", src: "Feeder O&I manuals" }],
    prerequisites: ["Segregated, dry, ventilated storage away from acids and organics", "SDS on site and staff trained"],
    retrofit: [],
    integrations: [{ name: "Pulsar Precision / Precision 30", note: "Required chemical.", status: "verified" }],
    services: ["Supply planning within service agreements", "Storage and handling training"],
    support: ["Chemical delivery, subject to owner confirmation of the current offering"],
    docs: [{ title: "Pulsar Plus briquettes Safety Data Sheet", type: "Safety data sheet", href: sources.pulsarBriquetteSDS.href, fileType: "PDF", status: "linked" }],
    faqs: [{ q: "Can we use another brand of cal hypo in the feeder?", a: "Pulsar's manuals state that other chemicals void the feeder warranty." }],
    related: ["pulsar-precision", "pulsar-precision-30"], specifiedWith: [{ slug: "pulsar-precision", status: "verified" }],
    relatedSolutions: ["replace-liquid-chlorine"],
    seoTitle: "Pulsar Plus Calcium Hypochlorite Briquettes | Supply for Pulsar Feeders, New York",
    seoDescription: "Pulsar Plus briquettes for Pulsar Precision feeders, with storage and handling guidance and supply through FreyTech in New York State outside NYC.",
    sourceUrls: [sources.pulsarBriquetteSDS.href], claimStatus: "verified", lastVerified: V, ownerApproved: false, ownerNotes: "Confirm FreyTech supplies chemicals.",
  },
  // ───────────────────────── Filtration ─────────────────────────
  {
    slug: "defender-regenerative-media-filter", name: "Defender Regenerative Media Filter", manufacturer: "neptune-benson", category: "filtration", status: "published", availability: "request",
    headline: "Fine filtration with far less backwash water, in a smaller footprint than sand",
    shortDescription: "Perlite regenerative media pressure filter from Neptune Benson (Xylem), NSF/ANSI 50 listed on all models; FreyTech installed Defenders at Ithaca College's 50-meter pool and Fairport High School.",
    overview: ["The Defender is a pressure-vessel regenerative media filter: water passes through a coat of perlite media held on flexible filter elements, and the media is periodically 'bumped' and re-coated rather than backwashed to drain. Perlite is loaded through a vacuum transfer unit. The result is very fine filtration, a compact vessel, and a large reduction in backwash water compared with sand filters. All Defender models are NSF/ANSI 50 listed per the manufacturer's technical data sheet.", "FreyTech supplied and installed Defender filters for Ithaca College's 50-meter pool and replaced the sand filter at Fairport High School with a Defender, according to our current website. Neptune Benson is now a Xylem brand; the current dealer relationship is being confirmed."],
    fit: { yes: ["Competition and university natatoriums pursuing clarity and water savings", "Renovations with limited mechanical-room space", "Facilities replacing original sand filters"], no: ["Facilities unable to staff the media-change routine", "Sites where a simple sand filter replacement meets the goal"] },
    problems: ["improve-filtration-water-clarity", "reduce-waste", "modernize-aging-equipment-room", "prepare-specifications-budgets"],
    applications: ["Natatoriums", "Municipal indoor pools", "School district pools"],
    facilities: ["colleges-universities", "k12-schools", "municipal-aquatic-centers", "ymca-community", "architects-engineers-public"],
    projectTypes: ["new-construction", "retrofit", "replacement"],
    features: ["Regenerative perlite media on flexible filter elements", "Bump-and-recoat cycle instead of frequent backwash", "Compact vessel relative to sand filtration"],
    benefits: ["Water clarity that coaches and members notice", "Reduced backwash water and associated heating loss", "Space recovered in the mechanical room"],
    models: [
      { name: "Defender Standard / Reduced Height", fit: "Main line for natatoriums and aquatic centers; 191–2,283 gpm per the manufacturer's data sheet." },
      { name: "Defender Assero", fit: "Smaller flows, 59–412 gpm." },
      { name: "Defender Virtuo", fit: "Designed for rooms with 8-foot ceilings; 216–1,712 gpm." },
    ],
    specs: [
      { k: "Filter type", v: "Pressure-vessel regenerative media filter using perlite; vacuum perlite transfer loading", src: "Defender Technical Data Sheet (Xylem, 2025)" },
      { k: "Flow ranges", v: "Standard/Reduced Height 191–2,283 gpm; Assero 59–412 gpm; Virtuo 216–1,712 gpm", src: "Defender Technical Data Sheet (Xylem, 2025)" },
      { k: "Listing", v: "NSF/ANSI 50 on all models", src: "Defender Technical Data Sheet (Xylem, 2025)" },
      { k: "Warranty", v: "Manufacturer states a 10-year warranty for Virtuo; confirm terms for other models", src: "Xylem Defender literature" },
    ],
    prerequisites: ["Engineer-confirmed flow and turnover under New York code", "Media handling and disposal routine", "Plan approval for filtration changes (6-1.8)"],
    retrofit: ["Direct replacement of sand filtration at Fairport High School per our current site", "Piping and pump changes are common; coordinate with the engineer"],
    integrations: [{ name: "BECSys7 automatic backwash", note: "Sequencing depends on filter valve design.", status: "commonly-considered" }, { name: "BECSys5 flow and pressure monitoring", note: "Optional monitoring of filter pressures and flow.", status: "commonly-considered" }],
    services: ["Evaluation of existing filtration and clarity problems", "Coordination with the engineer of record", "Supply, installation, and start-up", "Operator training on media handling"],
    support: ["Service and parts", "Warranty coordination"],
    docs: [{ title: "Defender family brochure (Xylem)", type: "Brochure", href: "https://amp.xylem.com/asset/a51a75b5-081f-40a0-91c9-f79e1a93a32a/Defender-Family-Brochure.pdf", fileType: "PDF", status: "linked" }, { title: "Defender Technical Data Sheet, imperial (Xylem)", type: "Specification sheet", href: "https://amp.xylem.com/asset/bb905bae-2d44-4a84-8aee-ad1c06b85e29/Defender-Technical-Datasheet-Imperial.pdf", fileType: "PDF", status: "linked" }, { title: "Neptune Benson brand page (Xylem)", type: "Product page", href: "https://www.xylem.com/en-us/brand/neptune-benson/", fileType: "Web", status: "linked" }],
    faqs: [{ q: "Is regenerative media harder to operate than sand?", a: "It has a different routine: periodic media changes and a bump cycle instead of backwash. Training at start-up covers it." }],
    related: ["becsys7", "becsys5", "stark-bulkheads"], specifiedWith: [{ slug: "becsys5", status: "commonly-considered" }, { slug: "becsys7", status: "commonly-considered" }],
    relatedSolutions: ["improve-filtration-water-clarity", "reduce-waste"],
    gallery: [{ src: "/images/projects/ithaca-college-50m-pool.webp", alt: "Ithaca College 50-meter pool, where FreyTech installed Defender filters and a Stark bulkhead", width: 922, height: 386, sourceUrl: "https://freytech.org/", status: "freytech-photo", license: "FreyTech project photo from current website; confirm rights" }],
    seoTitle: "Defender Regenerative Media Pool Filter | Installed by FreyTech in New York",
    seoDescription: "Defender regenerative media filtration for commercial pools: how it works, fit, and FreyTech's installations at New York colleges and school districts outside NYC.",
    sourceUrls: ["https://www.xylem.com/en-us/brand/neptune-benson/", "https://amp.xylem.com/asset/bb905bae-2d44-4a84-8aee-ad1c06b85e29/Defender-Technical-Datasheet-Imperial.pdf", "https://freytech.org/"], claimStatus: "partially-verified", lastVerified: V, ownerApproved: false, ownerNotes: "Product facts verified against Xylem literature. Confirm current dealer relationship with Xylem/Neptune Benson and permission for photo.",
  },
  // ───────────────────────── Deck, accessibility, safety ─────────────────────────
  {
    slug: "aqua-creek-pool-lifts", name: "Aqua Creek Pool Lifts", manufacturer: "aqua-creek", category: "accessibility-safety", subcategory: "Accessibility", status: "published", availability: "request",
    headline: "Accessible pool entry for every body of water",
    shortDescription: "Battery-powered pool and spa lifts from Aqua Creek Products, described by the manufacturer as ADA compliant and UL safety certified. Series: Pro Pool, Mighty, Revolution, EZ, and Spa.",
    overview: ["Aqua Creek Products (Missoula, Montana) manufactures battery-powered pool and spa lifts. The manufacturer describes its lifts as ADA compliant and UL safety certified and states it was the first pool lift manufacturer to have its lifts independently verified to meet ADA regulations. FreyTech's current website lists Aqua Creek as a represented brand and historically supplied lifts and retrofit kits to New York facilities.", "Current series per the manufacturer's 2026 lift guide: Pro Pool (Admiral, Ranger 2, Portable Pro Pool 2), Mighty (Mighty 400, Mighty 600, Voyager), Revolution (XL, XL Deep Draft, Scout Excel), EZ (Power EZ 2), and Spa (Neptune, Nebula, Nano). Capacities below are the manufacturer's."],
    fit: { yes: ["Any public pool or spa requiring an accessible means of entry", "Facilities replacing aging or non-compliant lifts"], no: ["Sites where deck structure cannot accept anchoring without engineering"] },
    problems: ["modernize-aging-equipment-room"],
    applications: ["Municipal, school, YMCA, hospitality, and healthcare pools and spas"],
    facilities: ["municipal-aquatic-centers", "k12-schools", "colleges-universities", "ymca-community", "hotels-resorts-hospitality", "healthcare-rehabilitation", "camps-seasonal"],
    projectTypes: ["new-construction", "retrofit", "replacement"],
    features: ["Battery-powered operation", "Fixed and portable models for pools and spas", "Manufacturer states ADA compliance and UL safety certification", "Independent ADA verification claimed by the manufacturer"],
    benefits: ["Accessible entry for each body of water", "Replacement path for aging lifts"],
    models: [
      { name: "Pro Pool series", fit: "Admiral 450 lb; Ranger 2 350 lb; Portable Pro Pool 2 350 lb (per manufacturer)." },
      { name: "Mighty series", fit: "Mighty 400 (400 lb), Mighty 600 (600 lb), Voyager (325 lb)." },
      { name: "Revolution series", fit: "Revolution XL 500 lb; XL Deep Draft 400 lb; Scout Excel 375 lb." },
      { name: "EZ series", fit: "Power EZ 2, 400 lb (manufacturer notes non-ADA)." },
      { name: "Spa lifts", fit: "Neptune and Nebula 400 lb; Nano." },
    ],
    specs: [{ k: "Weight capacities", v: "325–600 lb by model, per manufacturer's 2026 lift guide", src: "Aqua Creek Lift Guide 2026" }, { k: "Power", v: "Battery", src: "Aqua Creek" }, { k: "Compliance statements", v: "\"ADA compliant & UL safety certified\" (manufacturer wording); Power EZ 2 is non-ADA", src: "Aqua Creek" }],
    aliases: ["Admiral", "Ranger 2", "Mighty 400", "Mighty 600", "Voyager", "Revolution XL", "Scout Excel", "Power EZ 2", "Titan 600", "Rebel", "Patriot"],
    prerequisites: ["Deck structure and anchoring review", "Confirmation of accessibility requirements with the design team"],
    retrofit: ["Anchor and deck conditions determine model selection"],
    integrations: [],
    services: ["Selection with the design team", "Supply and installation coordination"],
    support: ["Parts and warranty coordination"],
    docs: [{ title: "Aqua Creek pool lifts", type: "Product page", href: "https://aquacreekproducts.com/category/pool-lifts/", fileType: "Web", status: "linked" }, { title: "Aqua Creek Lift Guide 2026", type: "Brochure", href: "https://ui309q.infiniteuploads.cloud/dlm_uploads/2026/09/Lift-Guide-Brochure-2026-Web.pdf", fileType: "PDF", status: "linked" }],
    faqs: [],
    related: ["stark-bulkheads"], specifiedWith: [],
    relatedSolutions: [],
    seoTitle: "ADA Pool Lifts for New York Commercial Pools | Aqua Creek, Supplied by FreyTech",
    seoDescription: "Battery-powered ADA pool and spa lifts for New York commercial facilities, selected and supplied by FreyTech outside NYC.",
    sourceUrls: ["https://aquacreekproducts.com/category/pool-lifts/", "https://freytech.org/products"], claimStatus: "partially-verified", lastVerified: V, ownerApproved: false, ownerNotes: "Product facts verified; confirm current dealer relationship and which series FreyTech carries.",
  },
  {
    slug: "stark-bulkheads", name: "Stark Movable Bulkheads (S.R.Smith)", manufacturer: "stark", category: "deck-equipment", subcategory: "Competition", status: "published", availability: "request",
    headline: "Reconfigure a competition pool for meets, practice, and programs",
    shortDescription: "One-piece composite movable bulkheads, now part of S.R.Smith (Fluidra). FreyTech installed a Stark bulkhead in Ithaca College's 50-meter pool.",
    overview: ["A movable bulkhead divides a long-course pool into shorter courses or separate program areas. FreyTech outfitted Ithaca College's 50-meter pool with a Stark bulkhead, according to our current website. Stark Bulkheads' assets were acquired by S.R.Smith, a Fluidra brand, in 2021; the line continues under S.R.Smith.", "S.R.Smith describes Stark bulkheads as monolithic one-piece composite structures moved by air chambers rather than rollers or tracks, built to custom sizes, compliant with FINA, NCAA, and USA Swimming requirements, and covered by a 25-year structural warranty. Specifications are project-specific."],
    fit: { yes: ["50-meter and long-course pools", "Facilities running concurrent programs in one pool"], no: ["Pools without the structure or gutter design to accept a bulkhead without engineering"] },
    problems: ["prepare-specifications-budgets"],
    applications: ["University and competition natatoriums"],
    facilities: ["colleges-universities", "municipal-aquatic-centers", "architects-engineers-public"],
    projectTypes: ["new-construction", "retrofit"],
    features: ["Monolithic one-piece composite construction", "Air-chamber movement; no rollers or tracks", "Custom sizes to pool width and gutter design", "FINA, NCAA, and USA Swimming compliance per the manufacturer", "25-year structural warranty per the manufacturer"],
    benefits: ["Multiple course lengths and simultaneous programs", "Meet flexibility for host facilities"],
    specs: [{ k: "Construction", v: "Monolithic one-piece composite; air-chamber movement", src: "S.R.Smith bulkheads page" }, { k: "Compliance", v: "FINA, NCAA, USA Swimming per manufacturer", src: "S.R.Smith bulkheads page" }, { k: "Warranty", v: "25-year structural warranty per manufacturer", src: "S.R.Smith bulkheads page" }, { k: "Dimensions", v: "Custom-built to the pool; no standard spec table published", src: "S.R.Smith" }],
    prerequisites: ["Structural and gutter compatibility confirmed by the engineer", "Program requirements from aquatics"],
    retrofit: ["Feasible in existing pools when structure and gutter allow"],
    integrations: [],
    services: ["Selection and coordination with the design team", "Installation coordination"],
    support: ["Parts and warranty coordination"],
    docs: [{ title: "S.R.Smith pool bulkheads (Stark)", type: "Product page", href: "https://www.srsmith.com/en-us/products/swimwall-systems-and-pool-bulkheads/pool-bulkheads/", fileType: "Web", status: "linked" }, { title: "S.R.Smith acquisition of Stark Bulkheads (2021)", type: "Product page", href: "https://www.srsmith.com/en-us/news/s-r-smith-acquires-assets-of-composite-aquatic-innovations-dba-stark-bulkheads/", fileType: "Web", status: "linked" }],
    faqs: [],
    related: ["defender-regenerative-media-filter"], specifiedWith: [],
    relatedSolutions: ["prepare-specifications-budgets"],
    image: { src: "/images/projects/ithaca-college-50m-pool.webp", alt: "Stark movable bulkhead in Ithaca College's 50-meter pool", width: 922, height: 386, sourceUrl: "https://freytech.org/", status: "freytech-photo", license: "FreyTech project photo from current website; confirm rights" },
    seoTitle: "Movable Pool Bulkheads for New York Competition Pools | Stark by S.R.Smith, Installed by FreyTech",
    seoDescription: "Stark movable bulkheads for competition pools, including FreyTech's installation at Ithaca College's 50-meter pool. New York State outside NYC.",
    sourceUrls: ["https://www.srsmith.com/en-us/products/swimwall-systems-and-pool-bulkheads/pool-bulkheads/", "https://freytech.org/"], claimStatus: "partially-verified", lastVerified: V, ownerApproved: false, ownerNotes: "Confirm current relationship with S.R.Smith and Ithaca College project details.",
  },
  // ───────────────────────── Water testing ─────────────────────────
  {
    slug: "taylor-test-kits", name: "Taylor Technologies Test Kits", manufacturer: "taylor", category: "water-testing-monitoring", status: "published", availability: "request",
    headline: "The manual reference every New York pool operator still needs",
    shortDescription: "Commercial 2000-series DPD and FAS-DPD test kits and reagents from Taylor Technologies (Fluidra); 18 Taylor kits are certified to NSF/ANSI/CAN 50 per the manufacturer.",
    overview: ["New York requires manual testing of pH and free and total chlorine at the beginning, during, and end of each swimming period with a DPD kit and reagents under one year old. Taylor Technologies test kits are the manual reference most operators use to verify and calibrate their controller. FreyTech supplies kits and reagents and trains operators to compare results with the controller."],
    fit: { yes: ["Every New York public pool", "Facilities standardizing testing across sites"], no: [] },
    problems: ["stabilize-water-chemistry", "reduce-manual-testing"],
    applications: ["Daily operator testing", "Controller calibration checks"],
    facilities: ["municipal-aquatic-centers", "k12-schools", "colleges-universities", "ymca-community", "hotels-resorts-hospitality", "healthcare-rehabilitation", "camps-seasonal", "waterparks-high-load"],
    projectTypes: ["replacement"],
    features: ["DPD and FAS-DPD methods", "Reagent replacement programs", "Kits for commercial service and operator use"],
    benefits: ["Reliable manual reference for controller calibration", "Meets the manual-testing requirement in 10 NYCRR 6-1.11 when used with fresh reagents"],
    specs: [{ k: "Commercial kits", v: "K-2005 (DPD), K-2006 (FAS-DPD), K-2005C / K-2006C 2 oz Service Complete kits, salt variants", src: "taylortechnologies.com" }, { k: "Certification", v: "18 Taylor kits certified to NSF/ANSI/CAN 50 per manufacturer", src: "Taylor NSF announcement" }, { k: "Reagent life", v: "Manufacturer: at least one year; replace seasonally. New York requires reagents under one year old.", src: "Taylor; 10 NYCRR 6-1.11" }],
    aliases: ["K-2005", "K-2006", "K-2005C", "K-2006C", "Taylor DPD", "FAS-DPD"],
    prerequisites: ["Reagents under one year old", "Operator training on method"],
    retrofit: [],
    integrations: [{ name: "BECSys controllers", note: "Manual results used for probe calibration; digital kits (SpinTouch, Lumiso) upload to BECSys.", status: "verified" }],
    services: ["Kit and reagent supply", "Testing and calibration training"],
    support: ["Reagent replacement within service agreements"],
    docs: [{ title: "Taylor Technologies", type: "Product page", href: "https://taylortechnologies.com/", fileType: "Web", status: "linked" }, { title: "NSF-certified Taylor kits", type: "Engineering resource", href: "https://taylortechnologies.com/blogs/news/nsf-certified-taylor-pool-spa-test-kits", fileType: "Web", status: "linked" }, { title: "How FAS-DPD tests free and combined chlorine", type: "Operator guide", href: "https://taylortechnologies.com/blogs/news/how-fas-dpd-tests-free-and-combined-chlorine-values", fileType: "Web", status: "linked" }],
    faqs: [{ q: "My controller and test kit disagree. Which is right?", a: "Start with fresh reagents and a careful manual test. If the kit is sound, clean and recalibrate the probe; if the probe is past its life, replace it." }],
    related: ["becs-replacement-sensors", "becsys5"], specifiedWith: [{ slug: "becsys5", status: "commonly-considered" }],
    relatedSolutions: ["stabilize-water-chemistry"],
    seoTitle: "Commercial Pool Test Kits and Reagents | Taylor Technologies, Supplied by FreyTech in New York",
    seoDescription: "Taylor Technologies DPD and FAS-DPD test kits and reagents for New York commercial pools, with operator training from FreyTech outside NYC.",
    sourceUrls: ["https://taylortechnologies.com/", "https://freytech.org/products"], claimStatus: "partially-verified", lastVerified: V, ownerApproved: false, ownerNotes: "Taylor's retail stockist locator does not list FreyTech (nearest: Spencerport). Confirm the commercial supply relationship or change wording to 'can supply'.",
  },
  // ───────────────────────── Parts ─────────────────────────
  {
    slug: "becs-replacement-sensors", name: "BECS Replacement Sensors and Flow-Cell Parts", manufacturer: "becs", category: "parts-accessories-replacement", subcategory: "Controller parts", status: "published", availability: "confirmed",
    headline: "Genuine pH, ORP, and temperature sensors and flow-cell parts for BECSys controllers",
    shortDescription: "Manufacturer sensors with a two-year warranty on pH/ORP/temperature, plus flow-cell components, supplied and installed by FreyTech.",
    overview: ["Probes are the wear item in any controller installation. BECS supplies proprietary pH and ORP sensors with a two-year warranty, temperature sensors, and machined flow-cell components. FreyTech stocks common parts and replaces them on preventive maintenance visits so calibration problems are prevented rather than discovered."],
    fit: { yes: ["Any facility running BECSys controllers"], no: ["Other controller brands (we can advise on compatible parts)"] },
    problems: ["stabilize-water-chemistry", "replace-obsolete-controller"],
    applications: ["Preventive maintenance", "Repair after probe failure"],
    facilities: ["municipal-aquatic-centers", "k12-schools", "colleges-universities", "ymca-community", "hotels-resorts-hospitality", "healthcare-rehabilitation", "camps-seasonal", "waterparks-high-load"],
    projectTypes: ["replacement"],
    features: ["Proprietary BECS pH and ORP sensors", "Temperature sensors and flow-cell parts", "Optional sensors (PPM, TDS, turbidity) per controller configuration"],
    benefits: ["Preserves controller warranty and accuracy", "Planned replacement instead of emergency calls"],
    specs: [{ k: "Sensor warranty (manufacturer)", v: "2 years pH, ORP, and temperature sensors; 1 year optional sensors and flow cell", src: "SLS-4333-H / TDS-4262" }],
    prerequisites: ["Controller model and sensor type"],
    retrofit: [],
    integrations: [{ name: "BECSys3/5/7", note: "Manufacturer parts.", status: "verified" }],
    services: ["Replacement and calibration on service visits"],
    support: ["Parts stocking for service-agreement customers", "BECS warranty coordination"],
    docs: [{ title: "BECSys5 brochure (warranty terms)", type: "Warranty", href: sources.becsys5Brochure.href, fileType: "PDF", status: "linked" }],
    faqs: [{ q: "How often should probes be replaced?", a: "It depends on water conditions and cleaning. Compare controller and manual readings monthly; replace when calibration no longer holds." }],
    related: ["becsys5", "becsys3", "taylor-test-kits"], specifiedWith: [],
    relatedSolutions: ["stabilize-water-chemistry"],
    seoTitle: "BECSys Replacement Probes and Flow-Cell Parts | FreyTech, New York",
    seoDescription: "Genuine BECS pH, ORP, and temperature sensors and flow-cell parts, supplied and installed by FreyTech for New York commercial pools outside NYC.",
    sourceUrls: [sources.becsys5Brochure.href], claimStatus: "verified", lastVerified: V, ownerApproved: false,
  },
  // ───────────────────────── Drafts (never rendered) ─────────────────────────
  { slug: "pulsar-guardtec", name: "Pulsar GuardTec Controller", manufacturer: "pulsar", category: "automated-controls", status: "draft", availability: "request", headline: "", shortDescription: "Pulsar's IoT pH/ORP controller with cloud portal. Draft: FreyTech recommends BECSys5; confirm whether GuardTec is offered.", overview: [], fit: { yes: [], no: [] }, problems: [], applications: [], facilities: [], projectTypes: [], features: [], benefits: [], specs: [], prerequisites: [], retrofit: [], integrations: [], services: [], support: [], docs: [], faqs: [], related: [], specifiedWith: [], relatedSolutions: [], seoTitle: "", seoDescription: "", sourceUrls: ["https://pulsarpools.com/products/guardtec/"], claimStatus: "partially-verified", lastVerified: V, ownerApproved: false, ownerNotes: "Decide when FreyTech recommends BECSys5 vs GuardTec." },
  {
    slug: "becs-co2-ph-control", name: "BECSys CO2 pH Feed System", manufacturer: "becs", category: "chemical-delivery-chlorination", subcategory: "pH control", status: "published", availability: "confirmed",
    aliases: ["BECS CO2 feeder", "carbon dioxide pH control", "CO2 feed"], keywords: ["acid-free pH control", "carbonic acid", "pH feed"],
    headline: "Carbon dioxide pH control that lowers pH without storing acid in the equipment room",
    shortDescription: "BECS Technology CO2 feed system in 5–50 and 20–200 SCFH sizes with diffuser or Venturi eductor; NSF/ANSI 50 listed per BECS.",
    overview: ["Carbon dioxide feed lowers pH by forming carbonic acid in the water rather than by dosing mineral acid. Operators like it because there is no acid to handle or store; the trade-off is that CO2 raises total alkalinity over time, so alkalinity has to be watched. BECS offers a CO2 feed system sized in two ranges, with a diffuser or Venturi eductor, regulator, heater, and cylinder switchover options, controlled by the BECSys controller's pH output."],
    fit: { yes: ["Facilities that want to eliminate acid handling", "Pools with adequate alkalinity management", "BECSys installations adding pH control"], no: ["Pools with chronically high alkalinity, where CO2 compounds the problem"] },
    problems: ["improve-chemical-safety", "stabilize-water-chemistry"],
    applications: ["Institutional pools with BECSys controllers", "Therapy pools where acid storage is a concern"],
    facilities: ["k12-schools", "colleges-universities", "ymca-community", "healthcare-rehabilitation", "municipal-aquatic-centers", "hotels-resorts-hospitality"],
    projectTypes: ["new-construction", "retrofit", "replacement"],
    features: ["Two size ranges: 5–50 SCFH and 20–200 SCFH", "Diffuser or Venturi eductor injection", "Regulator, heater, and cylinder switchover options", "NSF/ANSI 50 listed per BECS"],
    benefits: ["No mineral acid stored or handled", "Smooth pH control under the BECSys controller", "Fewer corrosive-chemical incidents in the equipment room"],
    specs: [{ k: "Capacity", v: "5–50 SCFH or 20–200 SCFH", src: "BECS SLS-6107-B" }, { k: "Injection", v: "Diffuser or Venturi eductor", src: "BECS SLS-6107-B" }, { k: "Listing", v: "NSF/ANSI 50 (CCS-14530) per BECS", src: "BECS SLS-6107-B" }, { k: "Warranty (manufacturer)", v: "1 year per BECS brochure", src: "BECS SLS-6107-B" }],
    prerequisites: ["BECSys controller with pH output", "CO2 cylinder or bulk supply location and ventilation", "Alkalinity monitoring plan"],
    retrofit: ["Commonly replaces acid metering pumps during a controller upgrade", "Watch total alkalinity trend after conversion"],
    integrations: [{ name: "BECSys3/5/7", note: "Controlled from the controller's pH output.", status: "verified" }],
    services: ["Specification and installation with the controller", "Commissioning and operator training"],
    support: ["Service and parts", "BECS warranty coordination"],
    docs: [{ title: "BECSys CO2 Feed System brochure (SLS-6107-B)", type: "Brochure", href: "https://www.becsys.com/wp-content/uploads/sites/2/2025/09/SLS-6107-B_CO2.pdf", fileType: "PDF", status: "linked" }],
    faqs: [{ q: "Does CO2 replace acid entirely?", a: "For pH control, yes, in most pools. Because CO2 adds alkalinity over time, some facilities still need occasional acid to manage alkalinity." }],
    related: ["becsys5", "becsys3"], specifiedWith: [{ slug: "becsys5", status: "verified" }],
    relatedSolutions: ["improve-chemical-safety"],
    seoTitle: "BECSys CO2 pH Feed System | Acid-Free pH Control for New York Pools",
    seoDescription: "BECS Technology CO2 feed system for pool pH control: sizes, listing, fit, and FreyTech installation and support in New York State outside NYC.",
    sourceUrls: ["https://www.becsys.com/wp-content/uploads/sites/2/2025/09/SLS-6107-B_CO2.pdf"], claimStatus: "verified", lastVerified: V, ownerApproved: false, ownerNotes: "Confirm FreyTech sells the BECS CO2 system.",
  },
  { slug: "spectrum-aquatics-deck-equipment", name: "Spectrum Aquatics Lifts and Deck Equipment", manufacturer: "spectrum", category: "deck-equipment", status: "draft", availability: "request", headline: "", shortDescription: "Listed on FreyTech's current site. Draft pending confirmation of current lines.", overview: [], fit: { yes: [], no: [] }, problems: [], applications: [], facilities: [], projectTypes: [], features: [], benefits: [], specs: [], prerequisites: [], retrofit: [], integrations: [], services: [], support: [], docs: [], faqs: [], related: [], specifiedWith: [], relatedSolutions: [], seoTitle: "", seoDescription: "", sourceUrls: ["https://www.spectrumproducts.com/"], claimStatus: "pending-verification", lastVerified: V, ownerApproved: false },
  { slug: "paragon-aquatics-deck-equipment", name: "Paragon Aquatics Deck and Competitive Equipment", manufacturer: "paragon", category: "deck-equipment", status: "draft", availability: "request", headline: "", shortDescription: "Starting platforms and deck equipment. Draft pending confirmation.", overview: [], fit: { yes: [], no: [] }, problems: [], applications: [], facilities: [], projectTypes: [], features: [], benefits: [], specs: [], prerequisites: [], retrofit: [], integrations: [], services: [], support: [], docs: [], faqs: [], related: [], specifiedWith: [], relatedSolutions: [], seoTitle: "", seoDescription: "", sourceUrls: [], claimStatus: "pending-verification", lastVerified: V, ownerApproved: false },
  { slug: "slip-md-anti-slip", name: "Slip MD Anti-Slip Treatment", manufacturer: "paragon", category: "deck-equipment", status: "excluded", availability: "discontinued", headline: "", shortDescription: "Listed on the old site; manufacturer site no longer resolves and no source exists. Excluded pending owner confirmation.", overview: [], fit: { yes: [], no: [] }, problems: [], applications: [], facilities: [], projectTypes: [], features: [], benefits: [], specs: [], prerequisites: [], retrofit: [], integrations: [], services: [], support: [], docs: [], faqs: [], related: [], specifiedWith: [], relatedSolutions: [], seoTitle: "", seoDescription: "", sourceUrls: [], claimStatus: "pending-verification", lastVerified: V, ownerApproved: false, ownerNotes: "slipmd.com no longer resolves." },
  { slug: "maytronics-dolphin-wave", name: "Maytronics Dolphin Wave Commercial Cleaners", manufacturer: "maytronics", category: "vacuums-cleaning", status: "draft", availability: "request", headline: "", shortDescription: "Robotic commercial pool cleaners. Draft: 2014 dealer notice on current site; confirm current relationship and models.", overview: [], fit: { yes: [], no: [] }, problems: [], applications: [], facilities: [], projectTypes: [], features: [], benefits: [], specs: [], prerequisites: [], retrofit: [], integrations: [], services: [], support: [], docs: [], faqs: [], related: [], specifiedWith: [], relatedSolutions: [], seoTitle: "", seoDescription: "", sourceUrls: ["https://www.maytronics.com/"], claimStatus: "pending-verification", lastVerified: V, ownerApproved: false },
];
